name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
      - name: backend build
        run: cd backend;npm install;ls -ltra
      - name: frontend build
        run: cd frontend;npm install;ls -ltra

